# Generated by Django 4.1.7 on 2023-04-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
