# Generated by Django 4.1.7 on 2023-04-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0003_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(default='NA', upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('Mech', 'Mechanical'), ('AI & DS', 'Artificial Intelligence')], max_length=10),
        ),
    ]
