# Generated by Django 4.1.7 on 2023-04-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0004_student_image_alter_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
