# Generated by Django 4.1.7 on 2023-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0006_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.AddField(
            model_name='student',
            name='studentimage',
            field=models.FileField(default=None, upload_to='studentimages'),
            preserve_default=False,
        ),
    ]
