# Generated by Django 4.1.7 on 2023-04-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmsapp', '0007_remove_student_image_student_studentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
